### ISSUE TITLE
Release for Symfony 2.*

### ISSUE THREAD

**Issue by edrush** [varspool/sphpdox#19]
I can't update some of my global SF2 packages since sphpdox master branch now requires Symfony 3 and there are no releases for that. Could a release of a former version for SF 2.\* be made? Or am I missing something? Thanks!

**Comment by andho** [comment]
@edrush makes sense.

My project depends on symfony 3.1.* components. Is it also possible to change the dependency to 3.* for latest version.

So that would mean two releases will be made. One that depends on symfony 2.8.* and another supporting symfony 3.*. I'm not sure whether it's really necessary to support symfony <2.8.

Also waiting for a release so I don't have to change my minimum-stability. Seems from the issue log there are not much issues but more feature requests.

**Comment by sabbelasichon** [comment]
@edrush I think we can close this issue. I did a first release but minimum requirement is Symfony Console 3.0. 2.8 is not supported. If you still need it, feel free to fork the project.
